#!/bin/bash
#/sbin/log-spindown

# Adding date and time to logfile
/bin/date >> /tmp/spindown.log

# Adding drive state, add a line (remove#) for each hdd!
/sbin/hdparm -C /dev/sda >> /tmp/spindown.log
#/sbin/hdparm -C /dev/sdb >> /tmp/spindown.log
#/sbin/hdparm -C /dev/sdc >> /tmp/spindown.log
#/sbin/hdparm -C /dev/sdd >> /tmp/spindown.log
#/sbin/hdparm -C /dev/sde >> /tmp/spindown.log
#/sbin/hdparm -C /dev/sdf >> /tmp/spindown.log
#/sbin/hdparm -C /dev/sdg >> /tmp/spindown.log

# Adding separator for easier reading
/bin/echo -------------------------------- >> /tmp/spindown.log

